<?php

use Cosmos\LaravelMonitor\Http\Controllers\CacheTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\DatabaseTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\DiagnosticsController;
use Cosmos\LaravelMonitor\Http\Controllers\ExceptionTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\ExternalRequestTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\ExternalServiceController;
use Cosmos\LaravelMonitor\Http\Controllers\HealthController;
use Cosmos\LaravelMonitor\Http\Controllers\LogTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\MailTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\MetricsController;
use Cosmos\LaravelMonitor\Http\Controllers\NotificationController;
use Cosmos\LaravelMonitor\Http\Controllers\PerformanceController;
use Cosmos\LaravelMonitor\Http\Controllers\QueueTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\RequestTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\ScheduleTelemetryController;
use Cosmos\LaravelMonitor\Http\Controllers\SettingsController;
use Cosmos\LaravelMonitor\Http\Controllers\StorageTelemetryController;
use Illuminate\Support\Facades\Route;

Route::get('health', HealthController::class);
Route::get('metrics/summary', [MetricsController::class, 'summary']);
Route::get('metrics/timeseries', [MetricsController::class, 'timeseries']);
Route::get('requests', [RequestTelemetryController::class, 'index']);
Route::get('queues', [QueueTelemetryController::class, 'index']);
Route::get('queues/{queue}/jobs', [QueueTelemetryController::class, 'jobs']);
Route::get('logs', [LogTelemetryController::class, 'index']);
Route::get('exceptions', [ExceptionTelemetryController::class, 'index']);
Route::put('exceptions/{hash}/status', [ExceptionTelemetryController::class, 'updateStatus']);
Route::get('schedules', [ScheduleTelemetryController::class, 'index']);
Route::get('database/latency', [DatabaseTelemetryController::class, 'latency']);
Route::get('performance', [PerformanceController::class, 'index']);
Route::get('cache', [CacheTelemetryController::class, 'index']);
Route::get('storage', [StorageTelemetryController::class, 'index']);
Route::get('external-requests', [ExternalRequestTelemetryController::class, 'index']);
Route::get('mail', [MailTelemetryController::class, 'index']);
Route::get('external-services', [ExternalServiceController::class, 'index']);
Route::post('external-services', [ExternalServiceController::class, 'store']);
Route::put('external-services/{id}', [ExternalServiceController::class, 'update']);
Route::delete('external-services/{id}', [ExternalServiceController::class, 'destroy']);
Route::post('external-services/{id}/check', [ExternalServiceController::class, 'check']);
Route::get('settings', [SettingsController::class, 'index']);
Route::put('settings', [SettingsController::class, 'update']);
Route::post('notifications/test', [NotificationController::class, 'test']);
Route::post('notifications/fcm/register', [NotificationController::class, 'registerFcmToken']);
Route::delete('notifications/fcm/register', [NotificationController::class, 'unregisterFcmToken']);
Route::post('diagnostics/logs/test', [DiagnosticsController::class, 'logTest']);
Route::post('diagnostics/exceptions/test', [DiagnosticsController::class, 'exceptionTest']);
Route::post('diagnostics/database/test-query', [DiagnosticsController::class, 'databaseTestQuery']);
